### ISSUE TITLE
comparability with latest version of virtue-mart

### ISSUE THREAD

**Issue by raramuridesign** [PaystackHQ/plugin-joomla-virtuemart-3#13]
Hi Support
We have tried to install this into our site and this has worked.

Virtuemart Version: 3.8.4 10335
Joomla: 3.9.22

We have a plugin called onepage checkout which seems to work fine with the paystack plugin installed.

However we get a problem where the currency is not recognized in the plugin / virtuemart to paystack

In our paystack account we have default currency to ZAR
In Virtuemart we have default currency to ZAR under the currency setup.

When we click confirm payment, the page goes to order complete, shows a modal with the following message

![image](https://user-images.githubusercontent.com/902376/99788871-05231600-2b22-11eb-8efa-3d4fc5250ced.png)

Why do we get this message when all the settings are ok?

M.

**Comment by damilola-paystack** [comment]
Hi @raramuridesign, we've been able to replicate this issue on our end. The plugin currently supports NGN only. We're working on a fix which should be pushed out soon.

**Comment by raramuridesign** [comment]
Hi @damilola-paystack Thanks for getting back, awesome. 
How long will it take to fix?

**Comment by damilola-paystack** [comment]
A fix should be available on or before next week Thursday.

**Comment by raramuridesign** [comment]
Thanks. Please update here when done.

**Comment by Andrew-Paystack** [comment]
Hey @raramuridesign, 

Just letting you know that a fix has been pushed for review. 

We should have it merged to master soon.

**Comment by raramuridesign** [comment]
Hi Guys, can you tell me if this code is ready, and if this 
https://github.com/PaystackHQ/plugin-joomla-virtuemart-3/commit/2cd40d9dd49f1ffcaa3fedb338ddea95b10996d7
solves the issue?
M.

@Andrew-Paystack @damilola-paystack
